### ISSUE TITLE
API keys gone when not debugging

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1103]
If I want to leave a local build on my device and walk around testing it, things like image upload fails b/c the environment variables are gone. This is a big setback for me b/c I'm constantly developing and testing my work, not using a TestFlight build.

Any way to re-enable this?

**Comment by Sherlouk** [comment]
100% intentional, not a bug. This was a limitation I set out in my original post, when using the scheme based env variables it's only when attached to debugger!

The work around for this is to enable the run-script and define env variables outside of schemes. So defining the BB build number and all three values

**Comment by rnystrom** [comment]
Hmm, do you have steps on how I can get it working? I tried using bash_profile like you outlined before, but that will only work for fastlane, not local builds.

We def need to figure this out, or revert the changes. Going to be very disruptive to local testing.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Leaving “bug” as this is def not something we want long term 😉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Did you also define the BB Build Number? If that's not also set it won't run the script - This is something we could/should make a bit more obvious.

Additionally, if the above steps really don't work then you could go to `Secrets.swift` and replace the `{GITHUBID}` etc in the `CI` enum with your values. That file is in the `.gitignore` so won't be commited (as long as you don't force it, obviously) - and this change is basically what the run-script does, just a bit more manual

Agree we should definitely fix this, can I propose a "Tech Debt" label for things like this, and fixing the mound of issues with SlackTextViewController? 😅

**Comment by BasThomas** [comment]
Think this is fixed right?

**Comment by rnystrom** [comment]
It’s not fixed, but I jut started using TestFlight builds

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
